export const API_WIKI = ".wikipedia.org/w/api.php";
export const langCode = {
    ab: "Abkhaz",
    aa: "Afar",
    af: "Afrikaans",
    ak: "Akan",
    sq: "Albanian",
    am: "Amharic",
    ar: "Arabic",
    an: "Aragonese",
    hy: "Armenian",
    as: "Assamese",
    av: "Avaric",
    ae: "Avestan",
    ay: "Aymara",
    az: "Azerbaijani",
    bm: "Bambara",
    ba: "Bashkir",
    eu: "Basque",
    be: "Belarusian",
    bn: "Bengali",
    bh: "Bihari",
    bi: "Bislama",
    bs: "Bosnian",
    br: "Breton",
    bg: "Bulgarian",
    my: "Burmese",
    ca: "Catalan; Valencian",
    ch: "Chamorro",
    ce: "Chechen",
    ny: "Chichewa; Chewa; Nyanja",
    zh: "Chinese",
    cv: "Chuvash",
    kw: "Cornish",
    co: "Corsican",
    cr: "Cree",
    hr: "Croatian",
    cs: "Czech",
    da: "Danish",
    dv: "Divehi; Maldivian;",
    nl: "Dutch",
    dz: "Dzongkha",
    en: "English",
    eo: "Esperanto",
    et: "Estonian",
    ee: "Ewe",
    fo: "Faroese",
    fj: "Fijian",
    fi: "Finnish",
    fr: "French",
    ff: "Fula",
    gl: "Galician",
    ka: "Georgian",
    de: "German",
    el: "Greek, Modern",
    gn: "Guaraní",
    gu: "Gujarati",
    ht: "Haitian",
    ha: "Hausa",
    he: "Hebrew (modern)",
    hz: "Herero",
    hi: "Hindi",
    ho: "Hiri Motu",
    hu: "Hungarian",
    ia: "Interlingua",
    id: "Indonesian",
    ie: "Interlingue",
    ga: "Irish",
    ig: "Igbo",
    ik: "Inupiaq",
    io: "Ido",
    is: "Icelandic",
    it: "Italian",
    iu: "Inuktitut",
    ja: "Japanese",
    jv: "Javanese",
    kl: "Kalaallisut",
    kn: "Kannada",
    kr: "Kanuri",
    ks: "Kashmiri",
    kk: "Kazakh",
    km: "Khmer",
    ki: "Kikuyu, Gikuyu",
    rw: "Kinyarwanda",
    ky: "Kirghiz, Kyrgyz",
    kv: "Komi",
    kg: "Kongo",
    ko: "Korean",
    ku: "Kurdish",
    kj: "Kwanyama, Kuanyama",
    la: "Latin",
    lb: "Luxembourgish",
    lg: "Luganda",
    li: "Limburgish",
    ln: "Lingala",
    lo: "Lao",
    lt: "Lithuanian",
    lu: "Luba-Katanga",
    lv: "Latvian",
    gv: "Manx",
    mk: "Macedonian",
    mg: "Malagasy",
    ms: "Malay",
    ml: "Malayalam",
    mt: "Maltese",
    mi: "Māori",
    mr: "Marathi (Marāṭhī)",
    mh: "Marshallese",
    mn: "Mongolian",
    na: "Nauru",
    nv: "Navajo, Navaho",
    nb: "Norwegian Bokmål",
    nd: "North Ndebele",
    ne: "Nepali",
    ng: "Ndonga",
    nn: "Norwegian Nynorsk",
    no: "Norwegian",
    ii: "Nuosu",
    nr: "South Ndebele",
    oc: "Occitan",
    oj: "Ojibwe, Ojibwa",
    cu: "Old Church Slavonic",
    om: "Oromo",
    or: "Oriya",
    os: "Ossetian, Ossetic",
    pa: "Panjabi, Punjabi",
    pi: "Pāli",
    fa: "Persian",
    pl: "Polish",
    ps: "Pashto, Pushto",
    pt: "Portuguese",
    qu: "Quechua",
    rm: "Romansh",
    rn: "Kirundi",
    ro: "Romanian, Moldavan",
    ru: "Russian",
    sa: "Sanskrit (Saṁskṛta)",
    sc: "Sardinian",
    sd: "Sindhi",
    se: "Northern Sami",
    sm: "Samoan",
    sg: "Sango",
    sr: "Serbian",
    gd: "Scottish Gaelic",
    sn: "Shona",
    si: "Sinhala, Sinhalese",
    sk: "Slovak",
    sl: "Slovene",
    so: "Somali",
    st: "Southern Sotho",
    es: "Spanish; Castilian",
    su: "Sundanese",
    sw: "Swahili",
    ss: "Swati",
    sv: "Swedish",
    ta: "Tamil",
    te: "Telugu",
    tg: "Tajik",
    th: "Thai",
    ti: "Tigrinya",
    bo: "Tibetan",
    tk: "Turkmen",
    tl: "Tagalog",
    tn: "Tswana",
    to: "Tonga",
    tr: "Turkish",
    ts: "Tsonga",
    tt: "Tatar",
    tw: "Twi",
    ty: "Tahitian",
    ug: "Uighur, Uyghur",
    uk: "Ukrainian",
    ur: "Urdu",
    uz: "Uzbek",
    ve: "Venda",
    vi: "Vietnamese",
    vo: "Volapük",
    wa: "Walloon",
    cy: "Welsh",
    wo: "Wolof",
    fy: "Western Frisian",
    xh: "Xhosa",
    yi: "Yiddish",
    yo: "Yoruba",
    za: "Zhuang, Chuang",
    zu: "Zulu"
};

export const mathsLang = {
    ab: "",
    aa: "",
    af: "Wiskunde",
    ak: "",
    sq: "Matematika",
    am: "ትምህርተ ሂሳብ",
    ar: "رياضيات",
    an: "Matematicas",
    hy: "Մաթեմատիկա",
    as: "গণিত",
    av: "",
    ae: "",
    ay: "Jakhu",
    az: "Riyaziyyat",
    bm: "",
    ba: "Математика",
    eu: "Matematika",
    be: "Матэматыка",
    bn: "গণিত",
    bh: "गणित",
    bi: "Matematikis",
    bs: "Matematika",
    br: "Matematik",
    bg: "Математика",
    my: "သင်္ချာ",
    ca: "Matemàtiques",
    ch: "Matematika",
    ce: "",
    ny: "",
    zh: "数学",
    cv: "Математика",
    kw: "Awgrym",
    co: "Matematica",
    cr: "",
    hr: "Matematika",
    cs: "Matematika",
    da: "Matematik",
    dv: "ރިޔާޟިއްޔާތު",
    nl: "Wiskunde",
    dz: "",
    en: "",
    eo: "Matematiko",
    et: "Matemaatika",
    ee: "",
    fo: "Støddfrøði",
    fj: "Fika",
    fi: "Matematiikka",
    fr: "Mathématiques",
    ff: "",
    gl: "Matemáticas",
    ka: "მათემატიკა",
    de: "Mathematik",
    el: "Μαθηματικά",
    gn: "Papapykuaa",
    gu: "ગણિત",
    ht: "Matematik",
    ha: "Lissafi",
    he: "מתמטיקה",
    hz: "",
    hi: "गणित",
    ho: "",
    hu: "Matematika",
    ia: "Mathematica",
    id: "Matematika",
    ie: "Matematica",
    ga: "Matamaitic",
    ig: "Ọmúmú-ónúọgụgụ",
    ik: "",
    io: "Matematiko",
    is: "Stærðfræði",
    it: "Matematica",
    iu: "ᓈᓴᐅᓯᕆᓂᓗᒃᑖᖅ",
    ja: "数学",
    jv: "Matématika",
    kl: "Matematikki",
    kn: "ಗಣಿತ",
    kr: "",
    ks: "رِیٲضی",
    kk: "Математика",
    km: "គណិតវិទ្យា",
    ki: "",
    rw: "",
    ky: "Математика",
    kv: "",
    kg: "",
    ko: "수학",
    ku: "Matematîk",
    kj: "",
    la: "Mathematica",
    lb: "Mathematik",
    lg: "Ekibalangulo",
    li: "Mathematiek",
    ln: "",
    lo: "ຄະນິດສາດ",
    lt: "Matematika",
    lu: "",
    lv: "Matemātika",
    gv: "Maddaght",
    mk: "Математика",
    mg: "Fanisana",
    ms: "Matematik",
    ml: "ഗണിതം",
    mt: "Matematika",
    mi: "",
    mr: "गणित",
    mh: "",
    mn: "Математик",
    na: "",
    nv: "Ałhiiʼnínáʼiidzóóh",
    nb: "",
    nd: "",
    ne: "गणित",
    ng: "",
    nn: "Matematikk",
    no: "Matematikk",
    ii: "",
    nr: "",
    oc: "Matematicas",
    oj: "",
    cu: "",
    om: "Herrega",
    or: "ଗଣିତ",
    os: "Математикæ",
    pa: "ਗਣਿਤ",
    pi: "गणितं",
    fa: "ریاضیات",
    pl: "Matematyka",
    ps: "شمېرپوهنه",
    pt: "Matemática",
    qu: "Yupay yachay",
    rm: "",
    rn: "",
    ro: "Matematică",
    ru: "Математика",
    sa: "गणितम्",
    sc: "Matemàtica",
    sd: "رياضي",
    se: "",
    sm: "Matematika",
    sg: "",
    sr: "Математика",
    gd: "Matamataig",
    sn: "Masvomhu",
    si: "ගණිතය",
    sk: "Matematika",
    sl: "Matematika",
    so: "Xisaab",
    st: "",
    es: "Matemáticas",
    su: "Matematika",
    sw: "Hisabati",
    ss: "Tekubala",
    sv: "Matematik",
    ta: "கணிதம்",
    te: "గణితం",
    tg: "Риёзиёт",
    th: "คณิตศาสตร์",
    ti: "",
    bo: "རྩིས་རིག",
    tk: "Matematika",
    tl: "Matematika",
    tn: "Dipalo",
    to: "",
    tr: "Matematik",
    ts: "Dyondzo-Tinhlayo",
    tt: "Математика",
    tw: "",
    ty: "",
    ug: "",
    uk: "Математика",
    ur: "ریاضی",
    uz: "Matematika",
    ve: "",
    vi: "Toán học",
    vo: "Matemat",
    wa: "Matematike",
    cy: "Mathemateg",
    wo: "Xayma",
    fy: "Wiskunde",
    xh: "I-Mathematics",
    yi: "מאטעמאטיק",
    yo: "Mathimátíkì",
    za: "Soqyoz"
};